#define DATA_FOLDER "D:/project data/data/"
#define TRAIN_FOLDER "D:/project data/data/train_images/"
#define TEMPLATE_FOLDER "D:/project data/data/templates/"
#define TEST_FOLDER "D:/project data/data/test_image"
#define RESULT_FOLDER "D:/project data/data/result_image/"
